# version: "3.6"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: webarber
      POSTGRES_USER: webarber
      POSTGRES_PASSWORD: webarber
    expose:
        - '5432'
    ports:
      - '5432:5432'
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
        tmpfs:
          size: 104857600

  api:
    build: .
    volumes:
      - .:/usr/src/webarber
    ports:
      - '8080:3000'
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: webarber
      DB_USERNAME: webarber
      DB_PASSWORD: webarber
    depends_on:
      - database
